default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Sant_Multi_Vendor_development
  username: postgres
  password: Power003
 
test:
  <<: *default
  database: Sant_Multi_Vendor_test
  username: postgres
  password: Power003

production:
  <<: *default
  database: Sant_Multi_Vendor_production
  username: Sant_Multi_Vendor
  password: <%= ENV["SANT_MULTI_VENDOR_DATABASE_PASSWORD"] %>
